---
title: "Clean data"
author : "Jeremy Wicquart"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: "cosmo"
    highlight: tango
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    toc_depth: 4
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

```

# Defining functions and packages

```{r base, fig.height=6, fig.width=12}

# 1. Recquired packages ----

library(tidyverse)
library(readxl)
library(zoo)

```

# Data cleaning

## Benthic data

```{r}

# 1. Initizalize the dataframe ----

data_benthos <- read_excel("./../data/01-raw_benthic-data_2005-2018_year-wise.xlsx", sheet = 1) %>% 
  mutate(Year = excel_sheets(path = "./../data/01-raw_benthic-data_2005-2018_year-wise.xlsx")[1])

# 2. Make a loop to bind all sheets ----

for (i in 2:13) {
  
  data_benthos <- data_benthos %>% 
    bind_rows(., read_excel("./../data/01-raw_benthic-data_2005-2018_year-wise.xlsx", sheet = i) %>% 
                 mutate(Year = excel_sheets(path = "./../data/01-raw_benthic-data_2005-2018_year-wise.xlsx")[i]))

}

data_benthos <- read_excel("./../data/01-raw_benthic-data_2019.xlsx", sheet = 1, skip = 1, n_max = 252) %>% 
  mutate(Year = as.character(Year)) %>% 
  select(-LCC) %>% # LCC = Live Coral Cover = sum of coral categories
  bind_rows(., data_benthos)

# 3. Clean the data ----

data_benthos <- data_benthos %>% 
  filter(!(is.na(Island))) %>% 
  select(-Region, -...21, -...22) %>% 
  pivot_longer("ACB":"Abiotic", names_to = "Category", values_to = "Cover") %>% 
  mutate(Year = str_extract(Year, "[[:digit:]]+")) %>% 
  filter(Cover != 0, !(is.na(Cover))) %>% 
  rename(Transect = LIT_Number, Site = Site_Number)

# 4. Export the data ----

write.csv2(data_benthos, "./../data/02-clean_benthic-data.csv", row.names = FALSE)
  
```

## Fish data

```{r}

# 1. Fish data from 2015 ----

# 1.1 Initizalize the dataframe --

data_fish_2015 <- read_excel("./../data/01-raw_fish-data_2015.xlsx", sheet = 1) %>% 
  mutate(Site = excel_sheets(path = "./../data/01-raw_fish-data_2015.xlsx")[1])

# 1.2 Make a loop to bind all sheets --

for (i in 2:21) {
  
  data_fish_2015 <- data_fish_2015 %>% 
    bind_rows(., read_excel("./../data/01-raw_fish-data_2015.xlsx", sheet = i) %>% 
                 mutate(Site = excel_sheets(path = "./../data/01-raw_fish-data_2015.xlsx")[i]))

}

# 1.3 Clean the data --

data_fish_2015 <- data_fish_2015 %>% 
  filter(!(is.na(S.No.))) %>% 
  select(-S.No., -Average, -SD, -SE, -...14, -...15, -...16, -...17, -...18) %>% 
  pivot_longer("Tr-1":"Tr-6", names_to = "Transect", values_to = "Abundance") %>% 
  mutate(Year = 2015)

```

```{r}

# 1. Fish data from 2016 ----

# 1.1 Initizalize the dataframe --

data_fish_2016 <- read_excel("./../data/01-raw_fish-data_2016.xlsx", sheet = 1) %>% 
  mutate(Site = excel_sheets(path = "./../data/01-raw_fish-data_2016.xlsx")[1])

# 1.2 Make a loop to bind all sheets --

for (i in 2:21) {
  
  data_fish_2016 <- data_fish_2016 %>% 
    bind_rows(., read_excel("./../data/01-raw_fish-data_2016.xlsx", sheet = i) %>% 
                 mutate(Site = excel_sheets(path = "./../data/01-raw_fish-data_2016.xlsx")[i]))

}

# 1.3 Clean the data --

data_fish_2016 <- data_fish_2016 %>% 
  filter(!(is.na(S.No.))) %>% 
  select(-S.No., -Average) %>% 
  pivot_longer("Tr-1":"Tr-6", names_to = "Transect", values_to = "Abundance") %>% 
  mutate(Year = 2016)

```

```{r}

# 1. Fish data from 2017 ----

# 1.1 Initizalize the dataframe --

data_fish_2017 <- read_excel("./../data/01-raw_fish-data_2017.xlsx", sheet = 1) %>% 
  mutate(Site = excel_sheets(path = "./../data/01-raw_fish-data_2017.xlsx")[1])

# 1.2 Make a loop to bind all sheets --

for (i in 2:21) {
  
  data_fish_2017 <- data_fish_2017 %>% 
    bind_rows(., read_excel("./../data/01-raw_fish-data_2017.xlsx", sheet = i) %>% 
                 mutate(Site = excel_sheets(path = "./../data/01-raw_fish-data_2017.xlsx")[i]))

}

# 1.3 Clean the data --

data_fish_2017 <- data_fish_2017 %>% 
  filter(!(is.na(S.No.))) %>% 
  select(-S.No., -Average) %>% 
  pivot_longer("Tr-1":"Tr-6", names_to = "Transect", values_to = "Abundance") %>% 
  mutate(Year = 2017)

```

```{r}

# 1. Fish data from 2018 ----

# 1.1 Initizalize the dataframe --

data_fish_2018 <- read_excel("./../data/01-raw_fish-data_2018.xlsx", sheet = 1) %>% 
  mutate(Site = excel_sheets(path = "./../data/01-raw_fish-data_2018.xlsx")[1])

# 1.2 Make a loop to bind all sheets --

for (i in 2:21) {
  
  data_fish_2018 <- data_fish_2018 %>% 
    bind_rows(., read_excel("./../data/01-raw_fish-data_2018.xlsx", sheet = i) %>% 
                 mutate(Site = excel_sheets(path = "./../data/01-raw_fish-data_2018.xlsx")[i]))

}

# 1.3 Clean the data --

data_fish_2018 <- data_fish_2018 %>% 
  filter(!(is.na(S.No.))) %>% 
  select(-S.No., -Average, -...12, -...13, -...14, -...15, -...16, -...17, -...18) %>% 
  pivot_longer("Tr-1":"Tr-6", names_to = "Transect", values_to = "Abundance") %>% 
  mutate(Year = 2018)

```

```{r}

# 1. Bind the dataframe for each years ----

data_fish <- data_fish_2015 %>% 
  bind_rows(., data_fish_2016) %>% 
  bind_rows(., data_fish_2017) %>% 
  bind_rows(., data_fish_2018) %>% 
  filter(Abundance != 0, !(is.na(Abundance))) %>% 
  mutate(Site = str_replace_all(Site, c("Kariyachalli" = "Kariyachllai",
                                        "Manoloiputti" = "Manoliputti",
                                        "Kurusadai" = "Krusadai",
                                        "poomarichan" = "Poomarichan",
                                        "Pullivaasal" = "Pullivasal",
                                        "kurusadai" = "Krusadai")))

# 2. Merge with site coordinates

data_fish <- read_excel("./../data/01-raw_fish-data_site-details.xlsx", sheet = 1) %>% 
  rename(Site = 1, Transect = 2, Longitude = 3, Latitude = 4) %>% 
  mutate(Site = na.locf(Site),
         Latitude = na.locf(Latitude), 
         Longitude = na.locf(Longitude)) %>% 
  left_join(data_fish, .)

# 3. Export the data ----

write.csv2(data_fish, "./../data/02-clean_fish-data.csv", row.names = FALSE)

# 4. Remove useless variables ----

rm(i, data_fish_2015, data_fish_2016, data_fish_2017, data_fish_2018)

```

# Reproducibility

```{r reprod}

# 1. Reproducibility ----

sessionInfo()

```

---
Jeremy WICQUART | jeremywicquart@gmail.com | `r format(Sys.time())`